using System.Numerics;
using System.Security.Cryptography;

namespace SecureChatTCP.Common;

public class DiffieHellman
{
    // 2048-bit safe prime generated by OpenSSL `dhparam 2048`, generator g = 2.
    // The leading "00" is the ASN.1 positive-integer sign byte (stripped when used).
    private static readonly BigInteger P = ParseHexBE(
        "00931F506D9A51E6F327D4D6E587D64005819BC72DE72A1FDF794951D28F24E32" +
        "F2C888D98E6427A208D4DD89A711E0CB6712BB9AE7B41FB3FE865169936A5ACB" +
        "27BE0DA0DE171912998C449A7CE2AEE0ECB927BBD2BCB1AD8B1BEF037A3D9BB5" +
        "178A7F77341A890DE916EDD6CCAC63E7E51D494544C530B86666103F3CF281FD6" +
        "8BDD1619A8825EDF450EA65C62ECBA16D0883B6E6B6EDAD25AFD4F4D6310C4AE" +
        "C8AFD7E194F6DA832C8AB74401108FFF4326D01D1A9450522944C64EA90F1CFA7" +
        "D8E31A3D6CB504A2E9388CF61D0562DDD0D7F8C8C3EE040EB25485E42F2CF947" +
        "336A9DFA088D9CFC8362F0AEDF28BD329DC4467C70C1377933EE6C5FE5EC547"
    );

    private static readonly BigInteger G = new(2);

    private readonly BigInteger _privateKey;

    public BigInteger PublicKey { get; }
    public BigInteger? SharedSecret { get; private set; }

    public DiffieHellman()
    {
        // Generate a random 2048-bit private key in range [2, P-2]
        var bytes = new byte[256];
        RandomNumberGenerator.Fill(bytes);
        bytes[255] &= 0x7F;                       // last bit to 0 -> positive rep in C#
        var raw = new BigInteger(bytes);
        _privateKey = (raw % (P - 3)) + 2;        // clamp to [2, P-2]

        PublicKey = BigInteger.ModPow(G, _privateKey, P);
    }

    public void ComputeSharedSecret(BigInteger otherPublicKey)
    {
        SharedSecret = BigInteger.ModPow(otherPublicKey, _privateKey, P);
    }

    // Returns 32-byte AES-256 key derived from the shared secret via SHA-256
    public byte[] DeriveAesKey()
    {
        if (SharedSecret is null)
            throw new InvalidOperationException("Call ComputeSharedSecret first.");
        return SHA256.HashData(SharedSecret.Value.ToByteArray());
    }

    // Parses a big-endian hex string (optionally with a leading 00 sign byte) into a BigInteger
    private static BigInteger ParseHexBE(string hex)
    {
        var bytes = Convert.FromHexString(hex); // big-endian bytes
        Array.Reverse(bytes);                   // flip to little-endian
        return new BigInteger(bytes);           // last byte is 0x00 → positive
    }
}
